{{- if and (not .Values.auth.existingSecret) .Values.auth.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tormenta-ai-proxy.fullname" . }}
  labels:
    {{- include "tormenta-ai-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiKey: {{ .Values.auth.apiKey | quote }}
{{- end -}}
